apiVersion: v1
kind: Service
metadata:
  name: togglemaster-flag-svc
  namespace: togglemaster
spec:
  selector:
    app: togglemaster-flag
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
