apiVersion: v1
kind: Service
metadata:
  name: togglemaster-auth-svc
  namespace: togglemaster
spec:
  selector:
    app: togglemaster-auth
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
