apiVersion: apps/v1
kind: Deployment
metadata:
  name: togglemaster-targeting
  namespace: togglemaster
  labels:
    app: togglemaster-targeting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: togglemaster-targeting
  template:
    metadata:
      labels:
        app: togglemaster-targeting
    spec:
      containers:
        - name: targeting
          image: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/togglemaster-targeting:latest
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-targeting-secret
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: rds-targeting-secret
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-targeting-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-targeting-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-targeting-secret
                  key: dbname
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 10
