name: CI — auth-service

on:
  push:
    branches: [main]
    paths:
      - "services/auth/**"
      - ".github/workflows/ci-auth.yml"
  pull_request:
    branches: [main]
    paths:
      - "services/auth/**"
permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci-reusable.yml
    with:
      service:           auth
      language:          go
      working_directory: services/auth
    secrets:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:     ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_ACCOUNT_ID:        ${{ secrets.AWS_ACCOUNT_ID }}
