name: CI — flag-service

on:
  push:
    branches: [main]
    paths:
      - "services/flag/**"
      - ".github/workflows/ci-flag.yml"
  pull_request:
    branches: [main]
    paths:
      - "services/flag/**"
permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci-reusable.yml
    with:
      service:           flag
      language:          python
      working_directory: services/flag
    secrets:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:     ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_ACCOUNT_ID:        ${{ secrets.AWS_ACCOUNT_ID }}
